---
title: "SRS_Assignment3"
output: pdf_document
date: "2023-03-23"
---
```{r}



data_m<-c(1, 1, 1, 15, 0, 3, 19, 54, 
                 4, 19, 62, 464, 76, 703, 1006)

#**** Coefficients: Indicator variables for the 4 Lists ******
# LA: Local Authority
# NGO: Non Governmental Organization
# PF: Police Force
# GO: Governmental Organization

LA<- c(rep(1,8),rep(0,7))
NGO<- c(rep(1,4),rep(0,4),rep(1,4),rep(0,3))
PF<-c(rep(c(1,0,1,0),3),c(1,0,1))
GO<-c(rep(c(1,1,0,0),3),c(1,1,0))

df<-data.frame(cbind(data_m,LA,NGO,PF,GO))
#***** 1.  Initial model ***********

```


```{r}
#**** 2. Model with interaction terms: using all interaction terms *****

model <- glm(data_m~LA+NGO+PF+GO+(LA+NGO+PF+GO)^2, family=poisson(link="log"))

summary(model)

# Estimate of the total population size
exp(summary(model)$coefficients[1,1])+sum(data_m)

# Confidence Interval for unobserved population
cat('\nThe 95% confidence interval for the unobserved population is ',
    '(',
    exp(b0-1.96*b0_se),
    ',',
    exp(b0+1.96*b0_se),
    ')')

```

```{r}
#**** 3. Model with interaction terms: Adding terms based on AIC ****

step_model<-step(model)
summary(step_model)
```


```{r}
#**** 4. Correlations btwn variables as a criterion to choose interactions ****
# Looking at correlations between variables 
#install.packages("psych")
library(psych)

  one<-which(df$LA==0 & df$NGO==0)
  two<-which(df$LA==1&df$NGO==0)
  three<-which(df$LA==0&df$NGO==1)
  four<-which(df$LA==1&df$NGO==1)
  
  pair<-matrix(c(sum(df$data_m[one]), sum(df$data_m[two]), 
                 sum(df$data_m[three]), sum(df$data_m[four])), nrow=2)
  
  tetrachoric(pair)
```
```{r}
#**** 5. Goodness of fit for selected model ****
```


```{r}
#**** 6. Checking model assumptions ****
library(ggplot2)
library(gridExtra)


# Plot 1: Residuals vs Fitted Values
res_fitted <- ggplot(data = step_model, aes(x = fitted(step_model), y = residuals(step_model))) + 
  geom_point() + 
  geom_smooth(method = "loess") + 
  labs(title = "Residuals vs Fitted Values", x = "Fitted Values", y = "Residuals")

# Plot 2: Normal Q-Q Plot
qq_plot <-ggplot(data = step_model, aes(sample = residuals(step_model))) +   geom_qq() + 
  geom_abline(slope = 1, intercept = 0) + 
  labs(title = "Normal Q-Q Plot")

# Plot 3: Scale-Location Plot
sca_loca <- ggplot(data = step_model, aes(x = fitted(step_model), y = sqrt(abs(residuals(step_model))))) + 
  geom_point() + 
  geom_smooth(method = "loess") + 
  labs(title = "Scale-Location Plot", x = "Fitted Values", y = "Sqrt(|Residuals|)")

# Plot 4: Residuals vs Leverage
res_leve <- ggplot(data = step_model, aes(x = hatvalues(step_model), y = residuals(step_model))) + 
  geom_point() + 
  geom_smooth(method = "loess") + 
  labs(title = "Residuals vs Leverage", x = "Leverage", y = "Residuals")

grid.arrange(res_fitted , qq_plot, sca_loca, res_leve,
             ncol = 2,
             nrow = 2)
```

